# This is the *first* configuration to import with configuration type: 'Migration Group'
uuid: 83170e08-b848-40be-898e-c78c9b12a1f9
langcode: en
status: true
dependencies: {  }
id: json_example
label: JSON Example
description: ''
source_type: ''
module: null
shared_configuration:
  source:
    urls: 'http://www.omdbapi.com/?s=space&type=movie&r=json&apikey=86e4b169'
